on:

  push:

    branches:

      - main

jobs:

  build-and-deploy:

    runs-on: windows-latest

     steps:

    - uses: actions/checkout@main

    - name: Deploy HTML Files to AppService - CMST386

      uses: azure/webapps-deploy@v1

      with:


        app-name: 'cmst386-dcastano'

        slot-name: 'production'
        
        publish-profile: ${{AppServiceCMST386}}
